apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fernandopires-iteris/meetup-argocd.git
    targetRevision: HEAD
    path: k8s/app

  destination:
    server: https://kubernetes.default.svc
    namespace: default
    